#!/bin/bash
dot tree.dot | gvpr -c -ftree.gv | neato -n -Tpng -o tree.png
dot -Tpng tree.dot -otree.png
dot balance.dot | gvpr -c -ftree.gv | neato -n -Tpng -o balance.png
dot -Tpng balance.dot -obalance.png

